version: '3.8'

services:
  globetrotter-server:
    build:
      context: ./server
    ports:
      - "5050:5050"
    env_file:
      - ./server/.env
    restart: unless-stopped

  globetrotter-client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    env_file:
      - ./client/.env
    restart: unless-stopped
